-- MySQL Script generated by MySQL Workbench
-- 05/03/16 00:25:51
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`card` (
  `card_ID` INT NOT NULL,
  `bonus_size` INT NULL,
  PRIMARY KEY (`card_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`address` (
  `address_ID` INT NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  `Street` VARCHAR(45) NULL,
  `House` VARCHAR(45) NULL,
  PRIMARY KEY (`address_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customers` (
  `customer_ID` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `e-mail` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `address_ID` INT NULL,
  `card_ID` INT NOT NULL,
  PRIMARY KEY (`customer_ID`),
  INDEX `Customers->card_idx` (`card_ID` ASC),
  INDEX `Customer->address_idx` (`address_ID` ASC),
  CONSTRAINT `Customers->card`
    FOREIGN KEY (`card_ID`)
    REFERENCES `mydb`.`card` (`card_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Customer->address`
    FOREIGN KEY (`address_ID`)
    REFERENCES `mydb`.`address` (`address_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`order` (
  `order_ID` INT NOT NULL,
  `customer_ID` INT NOT NULL,
  `price` INT NULL,
  `orderSize` INT NULL,
  PRIMARY KEY (`order_ID`),
  INDEX `order->customer_idx` (`customer_ID` ASC),
  CONSTRAINT `order->customer`
    FOREIGN KEY (`customer_ID`)
    REFERENCES `mydb`.`customers` (`customer_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pizzas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pizzas` (
  `pizza_ID` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NULL,
  `price` INT NULL,
  PRIMARY KEY (`pizza_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orderComponents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`orderComponents` (
  `orderComponents_ID` INT NOT NULL AUTO_INCREMENT,
  `quantity` INT NOT NULL,
  `pizza_ID` INT NOT NULL,
  `order_ID` INT NULL,
  PRIMARY KEY (`orderComponents_ID`),
  INDEX `orderComponents->order_idx` (`order_ID` ASC),
  INDEX `orderComponent->pizza_idx` (`pizza_ID` ASC),
  CONSTRAINT `orderComponents->order`
    FOREIGN KEY (`order_ID`)
    REFERENCES `mydb`.`order` (`order_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `orderComponent->pizza`
    FOREIGN KEY (`pizza_ID`)
    REFERENCES `mydb`.`pizzas` (`pizza_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
